[General]
background=background.jpg
type=image
color=#050510
font=JetBrainsMono Nerd Font
fontSize=13
headerText=GARCHY CYBER // NEURAL MATRIX 144Hz
accentColor=#00f5ff
goldColor=#f43f5e
textColor=#f8fafc
subtextColor=#cbd5e1
cardBg=#e6050512
inputBg=#f202020a
errorColor=#ff0055
successColor=#00ffaa
borderRadius=10
placeholderText=󰌾  [ ENTER NEURAL KEY ]
sentinelStatus=CYBERNETIC TELEMETRY: OPTIMAL [144Hz]
timeFormat=hh:mm:ss
dateFormat=dddd, d MMMM yyyy
