monitor = , preferred, auto, 1

$terminal = kitty
$menu = rofi -show drun
$fileManager = thunar

# Universal graphics hints
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = WLR_NO_HARDWARE_CURSORS,1
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11,*

# Live Environment Autostart
exec-once = waybar
exec-once = awww-daemon
exec-once = sleep 1 && /usr/bin/garchy-gui-installer

# Keybindings
bind = SUPER, Return, exec, kitty
bind = SUPER, T, exec, kitty
bind = SUPER, E, exec, thunar
bind = SUPER, Q, killactive,
bind = SUPER, Space, exec, /usr/bin/garchy-gui-installer
bind = SUPER, Escape, exit,

# Window Rules
windowrulev2 = float, title:(.*Garchy OS.*)
windowrulev2 = center, title:(.*Garchy OS.*)
windowrulev2 = size 920 640, title:(.*Garchy OS.*)

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(00f0ffee) rgba(fbbf24ee) 45deg
    col.inactive_border = rgba(1e293baa)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = false
    }
}
