[General]
background=background.jpg
type=image
color=#080d1a
font=JetBrainsMono Nerd Font
fontSize=13
headerText=GARCHY OS // ELEGANCE MATRIX
accentColor=#60a5fa
goldColor=#fbbf24
textColor=#f8fafc
subtextColor=#94a3b8
cardBg=#e6080d1a
inputBg=#f204070f
errorColor=#f43f5e
successColor=#34d399
borderRadius=12
placeholderText=󰌾  [ Enter Password ]
sentinelStatus=SECURITY SUBSYSTEM: OPTIMAL [100%]
timeFormat=hh:mm:ss
dateFormat=dddd, d MMMM yyyy
