[General]
background=background.jpg
type=image
color=#050914
font=JetBrainsMono Nerd Font
fontSize=13
headerText=GARCHY OS // CEPHALON CORE
accentColor=#00f0ff
goldColor=#fbbf24
textColor=#f1f5f9
subtextColor=#94a3b8
cardBg=#e6050914
inputBg=#f203060f
errorColor=#f43f5e
successColor=#34d399
borderRadius=10
placeholderText=󰌾  [ ENTER ACCESS CIPHER ]
sentinelStatus=CEPHALON SECURITY MATRIX: ACTIVE [100%]
timeFormat=hh:mm:ss
dateFormat=dddd, d MMMM yyyy
