[General]
background=background.jpg
type=image
color=#020b05
font=JetBrainsMono Nerd Font
fontSize=13
headerText=GARCHY TERMINAL // KERNEL TTY1
accentColor=#22c55e
goldColor=#10b981
textColor=#ecfdf5
subtextColor=#6ee7b7
cardBg=#e6020c06
inputBg=#f2010502
errorColor=#ef4444
successColor=#22c55e
borderRadius=8
placeholderText=󰌾  [ [sudo] password for operator ]
sentinelStatus=ROOT PRIVILEGE SUBSYSTEM: READY [0 err]
timeFormat=hh:mm:ss
dateFormat=dddd, d MMMM yyyy
