# ~/.config/kitty/kitty.conf

font_family      "JetBrainsMono Nerd Font"
font_size        12.5
line_height      1.08
bold_font        auto
italic_font      auto
bold_italic_font auto

background_opacity 1.0
background_blur 0
window_padding 5

cursor_shape block
cursor_beam_thickness 2
cursor_color #8bf7b4
cursor_text_color #08131a

scrollback_lines 100000
scrollback_pager_command less

experimental_opengl yes
vsync yes
draw_bold_text_with_bright_colors yes
allow_remote_control yes

# Color Scheme (Managed via theme.conf)
include theme.conf

window_title_format kitty: {title} — {cwd}
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+f toggle_fullscreen

enable_layout_snap yes
mouse_hide_wait 2.0
draw_shadow yes
shadow_offset_x 0
shadow_offset_y 0
shadow_blur 16
shadow_color #00000080
