foreground   #e0f8e5
background   #0f1a14
selection_foreground #0f1a14
selection_background #50fa7b
url_color #8be9fd
cursor #50fa7b
cursor_text_color #0f1a14

active_tab_background   #14261c
active_tab_foreground   #e0f8e5
inactive_tab_background #0f1a14
inactive_tab_foreground #4e7a5e

color0  #0a120e
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #50fa7b
color5  #ff79c6
color6  #8be9fd
color7  #e0f8e5
color8  #1e3c2d
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #50fa7b
color13 #ff92df
color14 #a4ffff
color15 #ffffff
