foreground   #ffffff
background   #111116
selection_foreground #111116
selection_background #ffffff
url_color #cbd5e1
cursor #ffffff
cursor_text_color #111116

active_tab_background   #1a1a22
active_tab_foreground   #ffffff
inactive_tab_background #111116
inactive_tab_foreground #555566

color0  #1a1a22
color1  #f7768e
color2  #e2e8f0
color3  #cbd5e1
color4  #ffffff
color5  #e2e8f0
color6  #ffffff
color7  #ffffff
color8  #333340
color9  #f7768e
color10 #e2e8f0
color11 #cbd5e1
color12 #ffffff
color13 #e2e8f0
color14 #ffffff
color15 #ffffff
